In [1]:
import numpy

In [2]:
!pip install numpy

In [ ]:
# The Np is alias. and Np is function which actual create array

import numpy as np

# Create array using numpy
# create a 1D array - (1 Dimention array)

arr1=np.array([1,2,3,4,5])
print(arr1)                     # In 1D it give 1 Braces of Bracket or array.
print(type(arr1))
print(arr1.shape)           # If the variable have 1D then then the shape of array is 1D.

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2=np.array([1,2,3,4,5])
print(arr2)
arr2.reshape(1,5)       # we defined two dimentional array . and in reshape it give 2 Braces of Bracket bcoz it 2D array.
                        # (1,5) means 1 Row and 5 are cloumn . if in array you defined [1,2,3,4,5] array if you reshape(1,4) then it gives arror bcoz you already give [1,2,3,4,5] means the reshape array should (1,5).

[1 2 3 4 5]


array([[1, 2, 3, 4, 5]])

In [9]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,4) 

ValueError: cannot reshape array of size 5 into shape (1,4)

In [11]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
# 2D Array

arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)             
print(arr2.shape)           # here why represent (2,5) bcoz there are 2 rows=[1,2,3,4,5]&[2,3,4,5,6] and 5 cloumn= inside in array 5 element are there

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2).reshape(5,1) # Here the rows is 5 and column is 1.

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [18]:
np.arange(0,10,2).reshape(1,5)

array([[0, 2, 4, 6, 8]])

In [21]:
np.ones((3,4))      # here np.ones means it present 1 in entire element and (3,4) means there are 3 rows and 4 column

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
## Identity Matrix - All the Diagonal element is 1 and other is 0

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Attributes of numpy array

arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of dimensions:",arr.ndim)
print("Size(number of elements):",arr.size)
print("Data Type:",arr.dtype)
print("Item size(in byte):",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size(number of elements): 6
Data Type: int64
Item size(in byte): 8


In [27]:
## Numpy Vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

# Element wise addition
print("Addition:",arr1+arr2)

# Element wise substraction
print("Substraction:",arr1-arr2)

# Element wise Multiplication
print("Multiplication:",arr1*arr2)

# Element wise Division
print("Division:",arr1 / arr2)

# Element in arr1[1] position and arr2[2] position addition

print("Addition of postion no:", arr1[1] + arr2[2])

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]
Addition of postion no: 32


In [29]:
# Universal function

arr=np.array([2,3,4,5,6])

# Squre root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sin
print(np.sin(arr))

# Natural Loh
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [30]:
## Array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("Array:\n",arr)



Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [41]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [32]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [33]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [42]:
## Modify Array element

arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [43]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [46]:
## Statistical Concept-Normalization
## to have a mean of 0 and standard deviation of 1

data= np.array([1,2,3,4,5])

# Calculate the mean and standard division

mean=np.mean(data)
print(mean)

std_div=np.std(data)
print(std_div)

# Normalization of data

normalization= (data - mean) / std_div
print("Normalization:",normalization)



3.0
1.4142135623730951
Normalization: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [51]:
data= np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean= np.mean(data)
print(mean)

# Median
median=np.median(data)
print(median)

# Standard Division
std_div=np.std(data)
print(std_div)

#Variance

variance=np.var(data)
print(variance)

5.5
5.5
2.8722813232690143
8.25


In [57]:
## Logical Operation

data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])